version: '3.8'

services:
  db:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-sept_2023}'
    volumes:
      - ./sept-2023-api-modules.db:/var/lib/postgresql/sept-2023
    env_file:
      - .env


  sept-2023-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    env_file:
      - .env
    command: >
      --requirepass '${REDIS_PASSWORD:-root}'
    restart: unless-stopped

  sept-2023-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "8000:9000"
      - "8001:9001"
    volumes:
      - ./sept-2023-s3:/usr/src/app/s3
    environment:
      MINIO_ROOT_USER: '${AWS_S3_ACCESS_KEY:-user}'
      MINIO_ROOT_PASSWORD: '${AWS_S3_SECRET_KEY:-password}'
    env_file:
      - .env
volumes:
  sept-2023-db:
  sept-2023-s3: